services:
  - type: web
    name: seminar-hall-booking
    runtime: node
    rootDir: .
    buildCommand: npm run build && cd server && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
